ignore:
  - "tests/**"

coverage:
  status:
    project:
      default:
        target: 0.70
        threshold: 2.0
    patch:
      default:
        informational: true
      source:
        target: 0.80
        threshold: 2.0
        paths:
          - "src/"
