# Particle Visualization
# Use with: --visualize flag

character:
  name: "Sophia Sterling"
  voice_type: "British Female"

tts:
  engine: "gtts"
  gtts_tld: "co.uk"

music:
  generator: "file"
  ducking:
    enabled: true
    music_volume_during_speech: 0.3
    music_volume_no_speech: 0.7

video:
  resolution: [1920, 1080]
  fps: 30
  codec: "h264"
  profile: "baseline"

# Particle Visualization
visualization:
  style: "particles"  # Flying particles
  primary_color: [255, 100, 100]  # Red
  secondary_color: [100, 100, 255]  # Blue
  background_color: [0, 0, 0]  # Black
  blur: 6
  sensitivity: 2.0

storage:
  base_dir: "./data"
  outputs_dir: "./data/outputs"
  cache_dir: "./data/cache"

processing:
  use_gpu: true





